// List of known temporary/fake email domains
const FAKE_EMAIL_DOMAINS = [
  // 10 minute mail services
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minemail.com',
  '20minutemail.com',
  '2prong.com',
  '30minutemail.com',
  '3d-painting.com',
  '4warding.com',
  '4warding.net',
  '4warding.org',
  '60minutemail.com',
  '7days-menu.com',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'pokemail.net',
  'sharklasers.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.info',
  
  // Mailinator and similar
  'mailinator.com',
  'mailinator2.com',
  'mailinator.net',
  'mailinator.org',
  'sogetthis.com',
  'spamhereonline.com',
  'spamherelots.com',
  'spamhereplease.com',
  'tempemail.com',
  'tempmail.org',
  'tempmail.net',
  'temp-mail.org',
  'tempail.com',
  'tempmailaddress.com',
  'tempinbox.com',
  
  // YOPmail
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'cool.fr.nf',
  'jetable.fr.nf',
  'nospam.ze.tc',
  'nomail.xl.cx',
  'mega.zik.dj',
  'speed.1s.fr',
  'courriel.fr.nf',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  
  // ThrowAwayMail
  'throwawaymail.com',
  'thrma.com',
  
  // Temporary email services
  'tempemails.net',
  'tempr.email',
  'throwaway.email',
  'zzz.com',
  'getnada.com',
  'armyspy.com',
  'cuvox.de',
  'dayrep.com',
  'fleckens.hu',
  'gustr.com',
  'jourrapide.com',
  'einrot.com',
  'teleworm.us',
  'superrito.com',
  'rhyta.com',
  
  // Disposable email
  'dispostable.com',
  'disposableemailaddresses.com',
  'mailnesia.com',
  'maildrop.cc',
  'mailnator.com',
  'moakt.com',
  'emailondeck.com',
  'fakeinbox.com',
  'mailcatch.com',
  'mytrashmail.com',
  'trashmail.com',
  'trashmail.org',
  'trashinbox.com',
  'trashymail.com',
  
  // Other temporary services
  'mohmal.com',
  'emailfake.com',
  'fakemailgenerator.com',
  'fakemail.net',
  'hide.biz.st',
  'mytemp.email',
  'temp-mailbox.com',
  'tempmailo.com',
  'temporaryemail.net',
  'temporaryemail.us',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'tfwno.gf',
  'thankyou2010.com',
  'mt2014.com',
  'mt2015.com',
  'mt2016.com',
  'mt2017.com',
  'thankyou2017.com',
  'trbvm.com',
  'x24hr.com',
  
  // More recent services
  'emailnax.com',
  '10mail.org',
  '20mail.it',
  '2mailnext.xyz',
  '30mail.ir',
  '3mail.ga',
  '4mail.cf',
  '5mail.cf',
  '6mail.cf',
  '7mail.ga',
  '8mail.cf',
  '9mail.cf',
  'amail4.me',
  'byom.de',
  'c2mail.org',
  'dc-hybrid.com',
  'email-fake.cf',
  'email-fake.ga',
  'email-fake.gq',
  'email-fake.ml',
  'email-fake.tk',
  'emailtemporar.ro',
  'emailtemporario.com.br',
  'emailto.de',
  'emailzilla.cf',
  'emailzilla.ga',
  'emailzilla.gq',
  'emailzilla.ml',
  'emailzilla.tk',
  'eelmail.com',
  'guerillamail.com',
  'h8s.org',
  'mail.by',
  'mailboxlayer.com',
  'maildu.de',
  'mailforspam.com',
  'mailfreeonline.com',
  'mailinator.uk',
  'mailinator.us',
  'mailinblack.com',
  'mailismagic.com',
  'mailmate.com',
  'mailnull.com',
  'mailsac.com',
  'mailscrap.com',
  'mailshell.com',
  'mailsiphon.com',
  'mailtemp.info',
  'mailtothis.com',
  'mailzilla.com',
  'mailzilla.org',
  'maxmail.dk',
  'meltmail.com',
  'messagebeamer.de',
  'mierdamail.com',
  'mintemail.com',
  'moburl.com',
  'mvrht.com',
  'mvrht.net',
  'nepwk.com',
  'neverbox.com',
  'no-spam.ws',
  'nobugmail.com',
  'noclickemail.com',
  'nogmailspam.info',
  'nomail.cf',
  'nomail.ga',
  'nomail.gq',
  'nomail.ml',
  'nomail.tk',
  'nomorespamemails.com',
  'noref.in',
  'notmailinator.com',
  'nowmymail.com',
  'objectmail.com',
  'obobbo.com',
  'odaymail.com',
  'opayq.com',
  'ordinaryamerican.net',
  'otherinbox.com',
  'ovpn.to',
  'owlpic.com',
  'pazeshkelahore.com',
  'pjkh.com',
  'plexvenet.de',
  'politikerclub.de',
  'pooae.com',
  'pjkh.tk',
  'protonmail.com', // Legitimate but often used for temp
  'put2.net',
  'putthisinyourspamdatabase.com',
  'pwrby.com',
  'qisdo.com',
  'qisoa.com',
  'qoika.com',
  'qqc.co',
  'qq.com', // Popular but often used for fake accounts
  'quickinbox.com',
  'rcpt.at',
  'reallymymail.com',
  'realtyalerts.ca',
  'recode.me',
  'recursor.net',
  'reliable-mail.com',
  'rhyta.com',
  'rklips.com',
  'rmqkr.net',
  'royal.net',
  'rppkn.com',
  'rtrtr.com',
  'ruffeweek.com',
  's0ny.net',
  'safe-mail.net',
  'safersignup.de',
  'safetymail.info',
  'safetypost.de',
  'sandelf.de',
  'savelife.ml',
  'saynotospams.com',
  'schafmail.de',
  'selfdestructingmail.com',
  'sendspamhere.com',
  'sharedmailbox.org',
  'shieldedmail.com',
  'shitmail.me',
  'shitware.nl',
  'shmeriously.com',
  'shortmail.net',
  'shut.name',
  'shut.ws',
  'sibmail.com',
  'sify.com',
  'skeefmail.com',
  'slaskpost.se',
  'slopsbox.com',
  'slushmail.com',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'soodonims.com',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambox.us',
  'spamcannon.com',
  'spamcannon.net',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamdecoy.net',
  'spameater.com',
  'spameater.org',
  'spamex.com',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.net',
  'spamfree24.org',
  'spamgoes.com',
  'spamgourmet.com',
  'spamgourmet.net',
  'spamgourmet.org',
  'spamhole.com',
  'spamify.com',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamspot.com',
  'spamthis.co.uk',
  'spamthisplease.com',
  'spamtrail.com',
  'spamtroll.net',
  'speed.1s.fr',
  'spikio.com',
  'spoofmail.de',
  'stuffmail.de',
  'supergreatmail.com',
  'supermailer.jp',
  'superrito.com',
  'tafmail.com',
  'tamtam.nl',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp.emeraldwebmail.com',
  'temp-mail.de',
  'temp-mail.org',
  'temp-mail.ru',
  'tempail.com',
  'tempalias.com',
  'tempemail.biz',
  'tempemail.com',
  'tempinbox.co.uk',
  'tempinbox.com',
  'tempmail.eu',
  'tempmail2.com',
  'tempmaildemo.com',
  'tempmailer.com',
  'tempmailer.de',
  'tempomail.fr',
  'temporarily.de',
  'temporarioemail.com.br',
  'temporaryemail.net',
  'temporaryforwarding.com',
  'temporaryinbox.com',
  'temporarymailaddress.com',
  'tempsky.com',
  'thanksnospam.info',
  'thankyou2010.com',
  'thecloudindex.com',
  'thisisnotmyrealemail.com',
  'throam.com',
  'throwam.com',
  'throwawayemailaddresses.com',
  'tinyurl.com',
  'tmail.ws',
  'tmpjr.com',
  'tmpmail.net',
  'tmpmail.org',
  'toomail.biz',
  'topranklist.de',
  'tradermail.info',
  'trash2009.com',
  'trash2010.com',
  'trash2011.com',
  'trashdevil.com',
  'trashdevil.de',
  'trashemail.de',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.me',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'turual.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'upliftnow.com',
  'uplipht.com',
  'uroid.com',
  'us.af',
  'venompen.com',
  'veryrealemail.com',
  'vfemail.net',
  'viditag.com',
  'viewcastmedia.com',
  'viewcastmedia.net',
  'viewcastmedia.org',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'walala.org',
  'walkmail.net',
  'wasteland.rfc822.org',
  'webemail.me',
  'webm4il.info',
  'weg-werf-email.de',
  'wegwerf-emails.de',
  'wegwerfadresse.de',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'wh4f.org',
  'whatiaas.com',
  'whatpaas.com',
  'whatsaas.com',
  'whyspam.me',
  'willhackforfood.biz',
  'willselldrugs.com',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yourdomain.com',
  'ypmail.webredirect.org',
  'yuurok.com',
  'yxzx.net',
  'zehnminutenmail.de',
  'zetmail.com',
  'zippymail.info',
  'zoemail.com',
  'zoemail.net',
  'zoemail.org',
  'zomg.info',
  'zsrcmp.com',
  'zzz.com',
];

/**
 * Validates if an email address is legitimate (not temporary/fake)
 * @param email - The email address to validate
 * @returns Object with isValid boolean and optional error message
 */
export const validateEmail = (email: string): { isValid: boolean; error?: string } => {
  // Basic email format validation
  const emailRegex = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;
  
  if (!email || !emailRegex.test(email)) {
    return {
      isValid: false,
      error: 'Please enter a valid email address format.'
    };
  }

  // Extract domain from email
  const domain = email.split('@')[1].toLowerCase();
  
  // Check if domain is in fake email list
  if (FAKE_EMAIL_DOMAINS.includes(domain)) {
    return {
      isValid: false,
      error: 'Please use a valid email address. Temporary email addresses are not allowed.'
    };
  }

  return {
    isValid: true
  };
};

/**
 * Check if domain appears to be a temporary email service
 * This is a fallback check for domains not in our list
 */
export const isLikelyTempEmail = (email: string): boolean => {
  const domain = email.split('@')[1].toLowerCase();
  
  // Common patterns for temporary email services
  const tempPatterns = [
    /temp/i,
    /trash/i,
    /throw/i,
    /fake/i,
    /spam/i,
    /guerr/i,
    /disp/i,
    /minute/i,
    /mail.*temp/i,
    /temp.*mail/i,
    /^[0-9]+min/i,
    /^[0-9]+hour/i
  ];

  return tempPatterns.some(pattern => pattern.test(domain));
};
