// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqehmuklqhcdzilrjjxm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxZWhtdWtscWhjZHppbHJqanhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4OTA0MDEsImV4cCI6MjA3MzQ2NjQwMX0.-k49In1bjkthgWgGdwmwxD7QFAldvdm797FiAK02Q-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});